# Generated by Django 6.0.3 on 2026-03-31 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('designer', 'Designer'), ('staff', 'Staff'), ('admin', 'Admin'), ('owner', 'Owner')], default='customer', max_length=20),
        ),
    ]
