# Generated by Django 6.0.3 on 2026-03-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('living_room', 'Living Room'), ('bedroom', 'Bedroom'), ('kitchen', 'Kitchen'), ('office', 'Office'), ('modular_furniture', 'Modular Furniture'), ('lighting_decor', 'Lighting & Decor')], max_length=50)),
                ('style', models.CharField(choices=[('modern', 'Modern'), ('classic', 'Classic'), ('minimalist', 'Minimalist'), ('bohemian', 'Bohemian'), ('industrial', 'Industrial')], max_length=50)),
                ('budget', models.CharField(choices=[('low', 'Low (Under 50k)'), ('medium', 'Medium (50k - 2L)'), ('high', 'High (Above 2L)')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='designs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
