# Generated by Django 6.0.3 on 2026-03-31 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
