# Generated by Django 6.0.3 on 2026-04-02 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0002_design_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='design',
            name='image',
        ),
    ]
