# Generated by Django 6.0.3 on 2026-03-31 07:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_designer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='budget_range',
            field=models.CharField(blank=True, choices=[('under_1L', 'Under ₹1 Lakh'), ('1L_3L', '₹1 Lakh - ₹3 Lakhs'), ('3L_5L', '₹3 Lakhs - ₹5 Lakhs'), ('5L_10L', '₹5 Lakhs - ₹10 Lakhs'), ('above_10L', 'Above ₹10 Lakhs')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='location',
            field=models.TextField(default='', help_text='Address for site visit'),
        ),
        migrations.AddField(
            model_name='booking',
            name='time_slot',
            field=models.CharField(choices=[('morning', 'Morning (9AM - 12PM)'), ('afternoon', 'Afternoon (12PM - 4PM)'), ('evening', 'Evening (4PM - 7PM)')], default='morning', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='visit_date',
            field=models.DateField(default=datetime.date(2026, 3, 31)),
            preserve_default=False,
        ),
    ]
